classDiagram
    class User {
        -int id
        -str username
        -str password
        -str email
        -int idrole
        -str token
        +__init__(id, username, password, email, idrole, token)
    }

    class Child {
        -int id
        -str child_name
        -float sleep_average
        -int treatment_id
        -str time
        +__init__(id, child_name, sleep_average, treatment_id, time)
    }

    
    class Tap {
        -int id
        -int child_id
        -int status_id
        -int user_id
        -str init
        +__init__(id, child_id, status_id, user_id, init)
    }

    
    class UserDAO {
        +getAllUsers() list
        +getUserByUsername(username) dict
        +login(identifier, password) dict
    }

    class ChildDAO {
        +getChilds(user) list
    }

    class TapDAO {
        +getTaps(Child) list
    }

    class ViewConsole {
        -DaoUserClient daoClient
        +viewShowMenu() int
        +viewGeneral()
        +viewLogin()
        +viewUser(user)
        +viewUserNotAutenticated()
        +viewChilds(list childs)
        +viewTaps(list taps)
    }


    %% Relacions
   
    
    UserDAO --> User : uses
    ChildDAO --> Child : uses
    ChildDAO --> User : uses
    TapDAO --> Tap : uses
    TapDAO --> Child : uses
    ViewConsole --> UserDAO : uses
    ViewConsole --> ChildDAO : uses
    ViewConsole --> TapDAO : uses

